name: Update Tide RSS Feed

on:
  schedule:
    - cron: '0 11 * * *'  # Runs at 7AM Eastern / 11AM UTC daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run RSS script
        run: python build_tide_wind_rss.py

      - name: Commit updated XML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tide-conditions.xml
          git commit -m "Auto-update tide and wind feed" || echo "No changes to commit"
          git push
